# Generated by Django 6.0.4 on 2026-07-21 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='details',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
