# Generated by Django 6.0.4 on 2026-07-21 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('announcement', 'Announcement'), ('personal', 'Personal')], default='personal', max_length=20),
        ),
    ]
