# Generated by Django 6.0.4 on 2026-07-18 09:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('check_in_time', models.TimeField(blank=True, null=True)),
                ('check_out_time', models.TimeField(blank=True, null=True)),
                ('hours_worked', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('present', 'Present'), ('late', 'Late'), ('leave', 'Leave')], default='present', max_length=20)),
            ],
            options={
                'verbose_name': 'Attendance Log',
                'verbose_name_plural': 'Attendance Logs',
                'db_table': 'attendance_logs',
                'ordering': ['-date'],
            },
        ),
    ]
