# Generated by Django 6.0.4 on 2026-07-25 18:28

import apps.settings.models.user_preference
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='notification_settings',
            field=models.JSONField(blank=True, default=apps.settings.models.user_preference.default_notification_settings),
        ),
    ]
