# Generated by Django 6.0.4 on 2026-07-24 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='users_employe_55e465_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_email_4b85f2_idx',
        ),
    ]
